### PR TITLE
Transition to basix library for finite element definitions

### LINKED ISSUE #33: Redesign FE interpolation (and get it working again for multi-point dofs)
Original `evaluate_dof(s)` using `ufc::function` was replaced by `tabulate_reference_dof_coordinates` + ~`map_dofs`~ (`transform_values` since #32). This made it basically defunct for multiple points dofs. Examples

```
element = FiniteElement("Nedelec 1st kind H(curl)", triangle, 2)
element = FiniteElement("Nedelec 1st kind H(curl)", tetrahedron, 3)
element = FiniteElement("Nedelec 2nd kind H(curl)", triangle, 2)
element = FiniteElement("Nedelec 2nd kind H(curl)", tetrahedron, 2)
```

which since that do not support interpolation because dofs are multi-point.

~Note that these examples in fact currently crash on a trivially fixable assertion when compiled.~

How to reproduce:

```
cat - > e.ufl <<EOF
element = FiniteElement("Nedelec 1st kind H(curl)", triangle, 2)
EOF

python3 -mffc e.ufl

# observe that implementation of transform_values is junk, will not compile
```

### LINKED ISSUE #175: tabulate_reference_dof_coordinates fails for some vector elements
Minimal failing example:
```python
import numpy as np
import ffc.codegeneration.jit
import ufl

cell = ufl.triangle
element = ufl.FiniteElement("N1curl", cell, 2)  # Order 1 works
compiled_element, module = ffc.codegeneration.jit.compile_elements([element])

compiled_e = compiled_element[0][0]

tdim = compiled_e.topological_dimension
space_dim = compiled_e.space_dimension
X = np.zeros([space_dim, tdim])
X_ptr = module.ffi.cast("double *", module.ffi.from_buffer(X))
result = compiled_e.tabulate_reference_dof_coordinates(X_ptr)
assert result == 0
```

### LINKED ISSUE #176: Get information needed to generate dof permutations from FIAT
The block size of the dof arrangement on each entity is needed by dolfinx to construct the dof map permuter.

This is done in a temporary, hacky way in https://github.com/FEniCS/ffcx/pull/174 but changes should be made in FIAT to get this information more cleanly

### LINKED ISSUE #277: Q3 space on hexes fails to compile
I'm seeing this here:

https://app.circleci.com/pipelines/github/FEniCS/dolfinx/5409/workflows/20a827b8-0a8c-4e7d-b40c-a8d6f825f0b8/jobs/19058

Running locally, it took forever trying to generate code, then I gave up and cancelled. Need to look into why this is so slow.

### PR DESCRIPTION
**Pull request by mscroggs**
Refactor everything to use Basix in the place of FIAT. This PR is twinned with FEniCS/dolfinx#1324.

Close #277. Close #175. Close #176. Close #33.

### CODE REVIEW

File: ffcx/codegeneration/ufc.h [hunk 1]
```diff
@@ -227,9 +214,20 @@ extern "C"
...
 
-    /// Boolean flag for affine 
+    /// Boolean flag for affine
     int is_affine;
 
+    /// Indicates whether permutation data needs to be passed into various
+    /// functions
+    bool needs_permutation_data;
+
+    /// TODO: doc
```
Comment (michalhabera) [inline ffcx/codegeneration/ufc.h:224]: Can you add docs, below also? UFC.h should be **the** source of information.

File: ffcx/ir/representation.py [hunk 2]
```diff
@@ -224,28 +212,26 @@ def _compute_dofmap_ir(ufl_element, element_numbers, dofmap_names):
...
-    ir["dof_reflection_entities"] = dof_permutations.reflection_entities(ufl_element)
-    ir["dof_face_tangents"] = dof_permutations.face_tangents(ufl_element)
+    ir["base_permutations"] = basix_element.base_permutations
 
     # Precompute repeatedly used items
-    num_dofs_per_entity = _num_dofs_per_entity(fiat_element)
-    entity_dofs = fiat_element.entity_dofs()
+    for i in basix_element.entity_dofs:
+        if max(i) != min(i):
+            raise RuntimeError("Elements withe different numbers of DOFs on subentities of the same dimension"
```
Comment (michalhabera) [inline ffcx/ir/representation.py:226]: Typos.

File: ffcx/ir/representation.py [hunk 3]
```diff
@@ -449,8 +428,6 @@ def _compute_integral_ir(form_data, form_index, prefix, element_numbers, integra
                 points = md["quadrature_points"]
                 weights = md["quadrature_weights"]
             elif scheme == "vertex":
-                # FIXME: Could this come from FIAT?
```
Comment (michalhabera) [inline ffcx/ir/representation.py:452]: Do not remove, but say it should come from basix.

File: test/conftest.py [hunk 4]
```diff
@@ -12,26 +12,26 @@
 elements = [("Lagrange", ufl.interval, 1),
             ("Lagrange", ufl.triangle, 1),
             ("Lagrange", ufl.tetrahedron, 1),
-            ("Lagrange", ufl.quadrilateral, 1),
-            ("Lagrange", ufl.hexahedron, 1),
+            # ("Lagrange", ufl.quadrilateral, 1),
```
Comment (michalhabera) [inline test/conftest.py:15]: Why are all these below commented?

File: test/test_elements.py [hunk 5]
```diff
@@ -108,27 +108,27 @@ class TestFunctionValues():
...
-                              lambda x: (-1.0 + x[0] + 3 * x[1] - 3 * x[0] * x[1], x[1] - 3 * x[1]**2),
-                              lambda x: (2 * x[0] - 3 * x[0] * x[1] - 3 * x[0] ** 2,
-                                         -2 + 3 * x[0] + 5 * x[1] - 3 * x[0] * x[1] - 3 * x[1]**2),
-                              lambda x: (-x[0] + 3 * x[0]**2,
-                                         1 - 3 * x[0] - x[1] + 3 * x[0] * x[1]),
-                              lambda x: (6 * x[0] - 3 * x[0] * x[1] - 6 * x[0]**2,
-                                         3 * x[1] - 6 * x[0] * x[1] - 3 * x[1]**2),
-                              lambda x: (3 * x[0] - 6 * x[0] * x[1] - 3 * x[0]**2,
-                                         6 * x[1] - 3 * x[0] * x[1] - 6 * x[1]**2)]
+    reference_triangle_rt1 = [lambda x: (-x[0], -x[1]), lambda x: (x[0] - 1, x[1]),
```
Comment (michalhabera) [inline test/test_elements.py:111]: Does these elements have a different dofs/basis now?

File: test/test_jit_cmaps.py [hunk 6]
```diff
@@ -26,12 +25,12 @@ def test_cmap_triangle(degree, compile_args):
     assert compiled_cmap[0].topological_dimension == 2
 
     # Reference coordinates X to basis
-    phi = np.zeros(((degree + 2) * (degree + 1)) // 2, dtype=np.float64)
-    phi_ptr = module.ffi.cast("double *", module.ffi.from_buffer(phi))
-    X = np.array([[1 / 3, 1 / 3]], dtype=np.float64)
-    X_ptr = module.ffi.cast("double *", module.ffi.from_buffer(X))
-    compiled_cmap[0].evaluate_basis_derivatives(phi_ptr, 0, X.shape[0], X_ptr)
-    assert np.isclose(sum(phi), 1.0)
+    # phi = np.zeros(((degree + 2) * (degree + 1)) // 2, dtype=np.float64)
```
Comment (michalhabera) [inline test/test_jit_cmaps.py:28]: Commented code

File: test/test_jit_cmaps.py [hunk 7]
```diff
@@ -46,7 +45,7 @@ def test_cmap_triangle(degree, compile_args):
 
 
 @pytest.mark.parametrize("degree", [1, 2])
-def test_cmap_quads(degree, compile_args):
+def xtest_cmap_quads(degree, compile_args):
```
Comment (michalhabera) [inline test/test_jit_cmaps.py:48]: Why disabled test?

File: test/test_jit_cmaps.py [hunk 8]
```diff
@@ -82,7 +81,7 @@ def test_cmap_quads(degree, compile_args):
 
 
 @pytest.mark.parametrize("degree", [1, 2, 3])
-def test_cmap_hex(degree, compile_args):
+def xtest_cmap_hex(degree, compile_args):
```
Comment (michalhabera) [inline test/test_jit_cmaps.py:84]: Why disabled test?

File: test/test_jit_elements.py [hunk 9]
```diff
@@ -7,13 +7,15 @@
 import numpy as np
 import pytest
 
-import ffcx
-import ffcx.codegeneration.jit
+# import ffcx
```
Comment (michalhabera) [inline test/test_jit_elements.py:10]: What is the point of this file now?

File: test/test_tabulate_tensor.py [hunk 10]
```diff
@@ -0,0 +1,252 @@
+# Copyright (C) 2020 Matthew Scroggs
```
Comment (michalhabera) [inline test/test_tabulate_tensor.py:1]: This file looks like it fits `test_jit_forms.py`, no?

**Review by michalhabera — CHANGES_REQUESTED** [review]

File: ffcx/codegeneration/ufc.h [hunk 11]
```diff
@@ -120,40 +104,43 @@ extern "C"
...
-    int (*tabulate_reference_dof_coordinates)(
-        double* restrict reference_dof_coordinates);
+        const double* restrict K);
+
+    /// Apply dof tranformations to some data
+    /// @param[in] data The data to be transformed
+    /// @param[in] cell_permutation An integer encoding the orientation of the
+    /// cell's entities
+    /// @param[in] dim The number of data items for each DOD
+    int (*apply_dof_transformation)(double* data, uint32_t cell_permutation,
```
[the remark this answers is not in the document]
Comment (mscroggs) [reply ffcx/codegeneration/ufc.h:122]: For more complicated situations such as face tangents, the DOF transformation is not a permutation, as it combines multiple DOFs to get the new DOF. It's probably more sensible though to call the functions permutations everywhere though to avoid confusion, so I'll rename stuff

[the remark this answers is not in the document]
Comment (mscroggs) [reply ffcx/codegeneration/ufc.h:122]: Actually, just noticed that there's `apply_dof_transformation` and `get_dof_permutation` and I guess it's useful to have different names to distinguish these

File: test/test_elements.py (hunk 5 above)
Comment (mscroggs) [reply test/test_elements.py:111]: Yes, we use the integral moment version of them now

File: test/conftest.py (hunk 4 above)
Comment (mscroggs) [reply test/conftest.py:15]: Quadrature and spectral elements are still not in basix yet, but I've turned the rest back on

File: test/test_jit_elements.py (hunk 9 above)
Comment (mscroggs) [reply test/test_jit_elements.py]: Good question. I've removed it

File: ffcx/ir/representation.py [hunk 12]
```diff
@@ -224,28 +210,26 @@ def _compute_dofmap_ir(ufl_element, element_numbers, dofmap_names):
...
-    ir["dof_reflection_entities"] = dof_permutations.reflection_entities(ufl_element)
-    ir["dof_face_tangents"] = dof_permutations.face_tangents(ufl_element)
+    ir["base_permutations"] = basix_element.base_permutations
 
     # Precompute repeatedly used items
-    num_dofs_per_entity = _num_dofs_per_entity(fiat_element)
-    entity_dofs = fiat_element.entity_dofs()
+    for i in basix_element.entity_dofs:
+        if max(i) != min(i):
+            raise RuntimeError("Elements with different numbers of DOFs on subentities of the same dimension"
```
Comment (michalhabera) [inline ffcx/ir/representation.py:224]: `raise NotImplementedError`

File: ffcx/ir/representationutils.py [hunk 13]
```diff
@@ -47,18 +46,18 @@ def id(self):
 def create_quadrature_points_and_weights(integral_type, cell, degree, rule):
     """Create quadrature rule and return points and weights."""
 
+    # from IPython import embed; embed()
```
Comment (michalhabera) [inline ffcx/ir/representationutils.py:49]: Leftover

File: ffcx/ir/representationutils.py [hunk 14]
```diff
@@ -47,18 +46,18 @@ def id(self):
...
     if integral_type == "cell":
-        (points, weights) = create_quadrature(cell.cellname(), degree, rule)
+        return create_quadrature(cell.cellname(), degree + 1, rule)
```
Comment (michalhabera) [inline ffcx/ir/representationutils.py:51]: Why is it `degree+1` compared to `degree`?

File: ffcx/ir/representationutils.py [hunk 15]
```diff
@@ -47,18 +46,18 @@ def id(self):
...
-        (points, weights) = create_quadrature("vertex", degree, rule)
+        return create_quadrature("vertex", degree + 1, rule)
     elif integral_type == "expression":
-        (points, weights) = (None, None)
-    else:
-        logging.exception("Unknown integral type: {}".format(integral_type))
-    return (points, weights)
+        return (None, None)
+
+    logging.exception(f"Unknown integral type: {integral_type}")
```
Comment (michalhabera) [inline ffcx/ir/representationutils.py:59]: Is this ever hit?

File: ffcx/codegeneration/finite_element_template.py [hunk 16]
```diff
@@ -20,42 +20,26 @@
...
-}}
-
-int evaluate_reference_basis_derivatives_{factory_name}(double * restrict reference_values,
-                                          int order, int num_points,
-                                          const double * restrict X)
-{{
-  {evaluate_reference_basis_derivatives}
-}}
-
 int transform_reference_basis_derivatives_{factory_name}(
```
Comment (michalhabera) [inline ffcx/codegeneration/finite_element_template.py:23]: Why is this method still in ufc?

Comment (mscroggs) [reply ffcx/codegeneration/finite_element_template.py:23]: It's still used in dolfinx, but could possibly be more neatly replaced by implementing Piola mapping functionality in Basix

Comment (mscroggs) [reply ffcx/codegeneration/finite_element_template.py:23]: I've made an issue: #299

File: ffcx/ir/representationutils.py (hunk 14 above)
Comment (mscroggs) [reply ffcx/ir/representationutils.py:51]: I don't remember, but it appears that everything still passes if I remove the `+ 1`. Perhaps there was a bug in Basix that we've since fixes

File: ffcx/ir/representationutils.py (hunk 15 above)
Comment (mscroggs) [reply ffcx/ir/representationutils.py:59]: no. I've changed it to a RuntimeError as in the function below to give a stronger warning that something is wrong if this is hit

**Review by michalhabera — APPROVED** [review]
